services:
  - type: web
    name: bico-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /swagger
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    buildCommand: null
    startCommand: null